[versions]
appcompat = "1.4.0"
activity-compose = "1.8.2"
app-update = "2.1.0"
app-update-ktx = "2.1.0"
material3 = "1.4.0"
material3-window-size = "1.4.0"
material3-adaptive-navigation-suite = "1.4.0"
navigation-compose = "2.7.7"

junit = "4.12"
espresso-core = "3.4.0"
ui-test-junit4 = "1.1.0"
ui-test-manifest = "1.6.2"

androidGradlePlugin = "8.9.1"
kotlin = "2.0.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
android-play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "app-update" }
android-play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update-ktx" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3-window-size" }
material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }


junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

